services:
  - type: web
    name: museum-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value:
      - key: DB_NAME
        value: akademik
